"""Virtual host management for the DevStack Docker stack.

This module provides :class:`VirtualHostManager`, a small, testable wrapper that
creates, lists and deletes nginx virtual hosts for the local development stack
defined in ``docker/docker-compose.yml``.

Key facts discovered from the compose / nginx configuration:

* The host ``./projects`` directory is bind-mounted into the **nginx** container
  at ``/var/www/projects`` (and into the **php** container at the same path).
* Per-project vhost configs live in ``./docker/vhosts`` on the host and are
  bind-mounted read-only into the nginx container at ``/etc/nginx/vhosts``.
* ``docker/nginx.conf`` includes ``/etc/nginx/vhosts/*.conf``.
* The PHP-FPM service is reachable from nginx as ``php:9000``.

All side effects that require elevated privileges (writing ``/etc/hosts``) or a
running Docker daemon (reloading nginx) are performed best-effort and never
raise: failures are collected as ``warnings`` so the caller can decide how to
proceed. This mirrors the graceful-degradation behaviour of
``server/services.py``.
"""

from __future__ import annotations

import os
import re
import shutil
import subprocess
from pathlib import Path

from services import ServiceManager

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
# Container-side root that mirrors the host ``./projects`` directory. Verified
# against docker/docker-compose.yml (`./projects:/var/www/projects:ro` on nginx).
PROJECTS_CONTAINER_ROOT = "/var/www/projects"

# Default nginx container name (matches ${COMPOSE_PROJECT_NAME:-devstack}-nginx in docker-compose.yml).
_compose_project = os.getenv("COMPOSE_PROJECT_NAME", "devstack")
NGINX_CONTAINER_NAME = os.getenv("DEVSTACK_NGINX_CONTAINER", f"{_compose_project}-nginx")

# Env-overridable hosts file path (handy for non-Linux / CI environments where
# /etc/hosts is not the right place, or where the user lacks permission).
HOSTS_FILE = os.getenv("DEVSTACK_HOSTS_FILE", "/etc/hosts")

# Allowed framework identifiers.
SUPPORTED_FRAMEWORKS = {"php", "laravel"}

# Regex for a sane virtual-host domain: one or more DNS labels separated by dots.
# Rejects empty strings, trailing dots, spaces, slashes and ".." traversal.
_DOMAIN_RE = re.compile(r"^(?!-)[A-Za-z0-9-]{1,63}(?<!-)(\.[A-Za-z0-9-]{1,63})*$")


# ---------------------------------------------------------------------------
# Template (Python str.format, literal braces escaped as {{ }})
# ---------------------------------------------------------------------------
# This is the single source of truth for rendering. It is also mirrored to
# docker/nginx-vhosts.conf so the template can be inspected / edited on disk;
# VirtualHostManager prefers the on-disk file when present and falls back to
# this constant otherwise.
NGINX_VHOST_TEMPLATE = """\
# DevStack virtual host - generated by server/virtual_hosts.py
# Template uses Python str.format(); placeholders: {domain}, {container_root}, {try_files}
server {{
    listen 80;
    listen [::]:80;
    server_name {domain};

    root {container_root};
    index index.php index.html;

    location / {{
        {try_files}
    }}

    location ~ \\.php$ {{
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }}

    # ---------------------------------------------------------------
    # SSL (Subtask 4): uncomment and provide certificates to enable HTTPS.
    # listen 443 ssl;
    # ssl_certificate     /etc/nginx/ssl/{domain}.crt;
    # ssl_certificate_key /etc/nginx/ssl/{domain}.key;
    # ---------------------------------------------------------------
}}
"""

# Pretty-URL behaviour differs per framework.
TRY_FILES_PHP = "try_files $uri $uri/ =404;"
TRY_FILES_LARAVEL = "try_files $uri $uri/ /index.php?$query_string;"


# ---------------------------------------------------------------------------
# Pure helpers (easy to unit test)
# ---------------------------------------------------------------------------
def validate_domain(domain: str) -> tuple[bool, str]:
    """Return ``(ok, error_message)`` for a candidate domain.

    Rejects ``None``/empty values, anything containing a path separator or
    ``..`` (path traversal), and anything that is not a valid DNS-like name.
    """
    if not domain or not isinstance(domain, str):
        return False, "domain is required and must be a string"
    if "/" in domain or "\\" in domain or ".." in domain:
        return False, "domain must not contain path separators or '..'"
    if not _DOMAIN_RE.match(domain):
        return False, (
            "domain must be a valid hostname (e.g. 'testapp.local' or 'api.example.com')"
        )
    return True, ""


def render_vhost(
    domain: str,
    container_root: str,
    framework: str = "php",
    template: str | None = None,
) -> str:
    """Render an nginx ``server`` block for ``domain``.

    Pure function: given the same inputs it always returns the same string,
    which makes it trivial to unit test. ``container_root`` is the path *inside*
    the nginx container (e.g. ``/var/www/projects/testapp.local``).
    """
    if framework not in SUPPORTED_FRAMEWORKS:
        framework = "php"
    try_files = TRY_FILES_LARAVEL if framework == "laravel" else TRY_FILES_PHP
    tpl = template if template is not None else NGINX_VHOST_TEMPLATE
    return tpl.format(
        domain=domain,
        container_root=container_root,
        try_files=try_files,
    )


def _starter_index_php(domain: str) -> str:
    """Return the contents of a friendly starter ``index.php`` page."""
    return (
        "<?php\n"
        "// DevStack managed virtual host\n"
        f"$domain = {domain!r};\n"
        "header('Content-Type: text/html; charset=utf-8');\n"
        "?>\n"
        "<!DOCTYPE html>\n"
        "<html lang=\"en\">\n"
        "<head>\n"
        "  <meta charset=\"utf-8\">\n"
        "  <title>DevStack &middot; <?= htmlspecialchars($domain) ?></title>\n"
        "  <style>\n"
        "    body { font-family: system-ui, sans-serif; margin: 4rem; color: #222; }\n"
        "    code { background: #f4f4f4; padding: 2px 6px; border-radius: 4px; }\n"
        "  </style>\n"
        "</head>\n"
        "<body>\n"
        "  <h1>DevStack</h1>\n"
        "  <p>Virtual host <code><?= htmlspecialchars($domain) ?></code> is working.</p>\n"
        "  <p>PHP version: <code><?= phpversion() ?></code></p>\n"
        "</body>\n"
        "</html>\n"
    )


# ---------------------------------------------------------------------------
# Manager
# ---------------------------------------------------------------------------
class VirtualHostManager:
    """Create, list and delete nginx virtual hosts on the DevStack stack."""

    def __init__(self, root: str | Path | None = None):
        # Project root is the parent of the ``server`` package directory.
        self.root = Path(root).resolve() if root else Path(__file__).resolve().parent.parent
        self.vhosts_dir = self.root / "docker" / "vhosts"
        self.projects_host_dir = self.root / "projects"
        self.hosts_file = HOSTS_FILE
        self.nginx_container = NGINX_CONTAINER_NAME
        # Ensure the vhosts directory exists so writes never fail on a missing dir.
        self.vhosts_dir.mkdir(parents=True, exist_ok=True)

    # ------------------------------------------------------------------
    # Template access
    # ------------------------------------------------------------------
    def _load_template(self) -> str:
        """Return the on-disk template if present, else the built-in constant."""
        file_tpl = self.root / "docker" / "nginx-vhosts.conf"
        if file_tpl.is_file():
            try:
                return file_tpl.read_text(encoding="utf-8")
            except OSError:
                pass
        return NGINX_VHOST_TEMPLATE

    # ------------------------------------------------------------------
    # Path helpers
    # ------------------------------------------------------------------
    def _config_path(self, domain: str) -> Path:
        return self.vhosts_dir / f"{domain}.conf"

    def _host_web_root(self, domain: str, root: str | None, framework: str) -> Path:
        """Resolve the host-side web root directory."""
        if root:
            path = Path(root)
            if not path.is_absolute():
                path = self.projects_host_dir / path
        elif framework == "laravel":
            path = self.projects_host_dir / domain / "public"
        else:
            path = self.projects_host_dir / domain
        return path.resolve()

    def _container_root(self, host_web_root: Path) -> tuple[str, list[str]]:
        """Map a host web root to its container-side path.

        Returns ``(container_root, warnings)``. The host ``./projects`` tree
        maps to ``/var/www/projects`` inside the container; anything outside
        that tree cannot be reliably mapped and falls back to the raw host path
        (with a warning).
        """
        warnings: list[str] = []
        try:
            rel = host_web_root.relative_to(self.projects_host_dir)
            return f"{PROJECTS_CONTAINER_ROOT}/{rel}", warnings
        except ValueError:
            warnings.append(
                f"Web root {host_web_root} is outside {self.projects_host_dir}; "
                f"using it verbatim as the container root (may not be reachable by nginx)."
            )
            return str(host_web_root), warnings

    # ------------------------------------------------------------------
    # /etc/hosts management (best-effort, never raises)
    # ------------------------------------------------------------------
    def _update_hosts(self, domain: str, add: bool) -> list[str]:
        """Add or remove a ``127.0.0.1 <domain>`` entry from the hosts file.

        Returns a list of warning strings (empty on success).
        """
        warnings: list[str] = []
        entry = f"127.0.0.1 {domain}"
        try:
            if not os.path.exists(self.hosts_file):
                warnings.append(f"Hosts file {self.hosts_file} does not exist; skipping.")
                return warnings
            with open(self.hosts_file, "r", encoding="utf-8") as fh:
                lines = fh.readlines()
        except (OSError, PermissionError) as exc:
            warnings.append(f"Could not read {self.hosts_file}: {exc}. Run with privileges to update hosts.")
            return warnings

        has_entry = any(entry in line for line in lines)

        if add and not has_entry:
            try:
                with open(self.hosts_file, "a", encoding="utf-8") as fh:
                    fh.write(f"{entry}\n")
            except (OSError, PermissionError):
                # Fall back to sudo; tolerate failure.
                try:
                    subprocess.run(
                        ["sudo", "sh", "-c", f"echo '{entry}' >> {self.hosts_file}"],
                        check=True,
                        stdout=subprocess.DEVNULL,
                        stderr=subprocess.PIPE,
                        timeout=15,
                    )
                except Exception as exc:  # noqa: BLE001 - best effort
                    warnings.append(
                        f"Could not add {entry} to {self.hosts_file}: {exc}. "
                        f"Add it manually or run the manager with privileges."
                    )
        elif not add and has_entry:
            new_lines = [line for line in lines if entry not in line]
            try:
                with open(self.hosts_file, "w", encoding="utf-8") as fh:
                    fh.writelines(new_lines)
            except (OSError, PermissionError):
                try:
                    tmp = "\n".join(line.rstrip("\n") for line in new_lines)
                    subprocess.run(
                        ["sudo", "sh", "-c", f"cat > {self.hosts_file} <<'EOF'\n{tmp}\nEOF"],
                        check=True,
                        stdout=subprocess.DEVNULL,
                        stderr=subprocess.PIPE,
                        timeout=15,
                    )
                except Exception as exc:  # noqa: BLE001 - best effort
                    warnings.append(
                        f"Could not remove {entry} from {self.hosts_file}: {exc}. "
                        f"Remove it manually or run the manager with privileges."
                    )
        return warnings

    # ------------------------------------------------------------------
    # nginx reload (best-effort, never raises)
    # ------------------------------------------------------------------
    def _reload_nginx(self) -> list[str]:
        """Reload nginx inside the container. Returns warning strings on failure."""
        warnings: list[str] = []
        try:
            sm = ServiceManager(root=self.root)
            cmd = sm.docker_cmd + [
                "-f", str(sm.compose_file),
                "exec", self.nginx_container,
                "nginx", "-s", "reload",
            ]
            result = sm._run(cmd)
            if not result.get("success"):
                warnings.append(f"nginx reload failed: {result.get('message')}")
        except Exception as exc:  # noqa: BLE001 - best effort
            warnings.append(f"nginx reload could not be attempted: {exc}")
        return warnings

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------
    def create(
        self,
        domain: str,
        root: str | None = None,
        framework: str = "php",
    ) -> dict:
        """Create a virtual host for ``domain``.

        Returns ``{"success", "domain", "root", "config_path", "warnings"}``.
        Side effects (hosts file, nginx reload) are best-effort and reported via
        ``warnings``; a failure there does not mark the whole operation failed.
        """
        warnings: list[str] = []
        ok, err = validate_domain(domain)
        if not ok:
            return {
                "success": False,
                "domain": domain,
                "root": None,
                "config_path": None,
                "warnings": [err],
            }

        if framework not in SUPPORTED_FRAMEWORKS:
            framework = "php"

        host_web_root = self._host_web_root(domain, root, framework)
        container_root, map_warnings = self._container_root(host_web_root)
        warnings.extend(map_warnings)

        # Create the web root on the host (and a public/ subdir for Laravel).
        try:
            host_web_root.mkdir(parents=True, exist_ok=True)
        except OSError as exc:
            return {
                "success": False,
                "domain": domain,
                "root": str(host_web_root),
                "config_path": None,
                "warnings": [f"Could not create web root {host_web_root}: {exc}"],
            }

        # Drop a starter index.php if one is not already present.
        index_file = host_web_root / "index.php"
        if not index_file.exists():
            try:
                index_file.write_text(_starter_index_php(domain), encoding="utf-8")
            except OSError as exc:
                warnings.append(f"Could not write starter index.php: {exc}")

        # Add the domain to /etc/hosts (best-effort).
        warnings.extend(self._update_hosts(domain, add=True))

        # Render and write the nginx vhost config.
        config_path = self._config_path(domain)
        try:
            rendered = render_vhost(
                domain, container_root, framework, template=self._load_template()
            )
            config_path.write_text(rendered, encoding="utf-8")
        except OSError as exc:
            return {
                "success": False,
                "domain": domain,
                "root": str(host_web_root),
                "config_path": str(config_path),
                "warnings": [f"Could not write vhost config: {exc}"],
            }

        # Reload nginx (best-effort).
        warnings.extend(self._reload_nginx())

        return {
            "success": True,
            "domain": domain,
            "root": str(host_web_root),
            "config_path": str(config_path),
            "warnings": warnings,
        }

    def delete(self, domain: str, remove_files: bool = False) -> dict:
        """Delete the virtual host for ``domain``.

        By default only the nginx config and the ``/etc/hosts`` entry are
        removed. Pass ``remove_files=True`` to also delete the project folder.
        """
        warnings: list[str] = []
        ok, err = validate_domain(domain)
        if not ok:
            return {"success": False, "domain": domain, "missing": False, "warnings": [err]}

        config_path = self._config_path(domain)
        if not config_path.exists():
            return {
                "success": False,
                "domain": domain,
                "missing": True,
                "warnings": [f"No vhost config found at {config_path}"],
            }

        # Determine the project folder to optionally remove.
        host_web_root = None
        try:
            content = config_path.read_text(encoding="utf-8")
            m = re.search(r"^\s*root\s+([^;]+);", content, re.MULTILINE)
            if m:
                container_root = m.group(1).strip()
                if container_root.startswith(PROJECTS_CONTAINER_ROOT):
                    rel = container_root[len(PROJECTS_CONTAINER_ROOT):].lstrip("/")
                    host_web_root = self.projects_host_dir / rel
        except OSError:
            host_web_root = None

        # Remove the config file.
        try:
            config_path.unlink()
        except OSError as exc:
            warnings.append(f"Could not remove config {config_path}: {exc}")

        # Remove the /etc/hosts entry (best-effort).
        warnings.extend(self._update_hosts(domain, add=False))

        # Optionally remove the project files.
        if remove_files and host_web_root is not None:
            try:
                shutil.rmtree(host_web_root, ignore_errors=True)
            except OSError as exc:
                warnings.append(f"Could not remove project files {host_web_root}: {exc}")

        # Reload nginx (best-effort).
        warnings.extend(self._reload_nginx())

        return {
            "success": True,
            "domain": domain,
            "missing": False,
            "removed_config": str(config_path),
            "removed_files": str(host_web_root) if remove_files else None,
            "warnings": warnings,
        }

    def list_all(self) -> list[dict]:
        """Scan the vhosts directory and return metadata for each host.

        Each entry is ``{domain, config_path, root, framework}`` where ``root``
        is the host-side path (mapped back from the container root) and
        ``framework`` is inferred from the rendered config.
        """
        results: list[dict] = []
        if not self.vhosts_dir.is_dir():
            return results

        for conf in sorted(self.vhosts_dir.glob("*.conf")):
            domain = conf.stem
            entry: dict = {
                "domain": domain,
                "config_path": str(conf),
                "root": None,
                "framework": "php",
            }
            try:
                content = conf.read_text(encoding="utf-8")
            except OSError:
                results.append(entry)
                continue

            # Prefer an explicit server_name if present, else the filename stem.
            m = re.search(r"^\s*server_name\s+([^;]+);", content, re.MULTILINE)
            if m:
                name = m.group(1).strip().split()[0]
                if name and name != "_":
                    entry["domain"] = name

            # Map the container root back to a host path.
            rm = re.search(r"^\s*root\s+([^;]+);", content, re.MULTILINE)
            if rm:
                container_root = rm.group(1).strip()
                if container_root.startswith(PROJECTS_CONTAINER_ROOT):
                    rel = container_root[len(PROJECTS_CONTAINER_ROOT):].lstrip("/")
                    entry["root"] = str(self.projects_host_dir / rel)
                else:
                    entry["root"] = container_root

            # Infer framework from the try_files directive.
            if "index.php?$query_string" in content:
                entry["framework"] = "laravel"
            else:
                entry["framework"] = "php"

            results.append(entry)

        return results


if __name__ == "__main__":
    import pprint

    pprint.pprint(VirtualHostManager().list_all())
